import { ItemEstoque } from '@/features/estoque/types/Estoque.types';

const subDays = (days: number) => {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d;
};

export const itensEstoqueMock: ItemEstoque[] = [
  {
    id: 'e-1',
    itemId: '3',
    itemNome: 'Camiseta Algodão Branca',
    itemSku: 'PROD-CAM-001',
    categoria: 'Produto Acabado',
    quantidadeAtual: 150,
    quantidadeMinima: 50,
    quantidadeReservada: 20,
    unidadeMedida: 'Unidade',
    localizacao: 'PRAT-A1',
    custoMedio: 15.5,
    valorTotal: 2325.0,
    ultimaMovimentacao: subDays(2),
  },
  {
    id: 'e-2',
    itemId: 'm-1',
    itemNome: 'Tecido Algodão Premium',
    itemSku: 'MAT-TEC-001',
    categoria: 'Matéria-Prima',
    quantidadeAtual: 45,
    quantidadeMinima: 100,
    quantidadeReservada: 10,
    unidadeMedida: 'Metro',
    localizacao: 'PRAT-C3',
    custoMedio: 22.0,
    valorTotal: 990.0,
    ultimaMovimentacao: subDays(1),
  },
  {
    id: 'e-3',
    itemId: '8',
    itemNome: 'Boné 5 Gomos Preto',
    itemSku: 'PROD-BON-001',
    categoria: 'Produto Acabado',
    quantidadeAtual: 12,
    quantidadeMinima: 20,
    quantidadeReservada: 0,
    unidadeMedida: 'Unidade',
    localizacao: 'PRAT-B2',
    custoMedio: 8.4,
    valorTotal: 100.8,
    ultimaMovimentacao: subDays(5),
  },
  {
    id: 'e-4',
    itemId: 'm-2',
    itemNome: 'Linha Costura Reforçada',
    itemSku: 'MAT-LIN-001',
    categoria: 'Matéria-Prima',
    quantidadeAtual: 300,
    quantidadeMinima: 50,
    quantidadeReservada: 0,
    unidadeMedida: 'Unidade',
    localizacao: 'GAV-D1',
    custoMedio: 2.15,
    valorTotal: 645.0,
    ultimaMovimentacao: subDays(10),
  },
  {
    id: 'e-5',
    itemId: 'm-3',
    itemNome: 'Tinta Serigrafia Preta 1kg',
    itemSku: 'MAT-TIN-001',
    categoria: 'Matéria-Prima',
    quantidadeAtual: 8,
    quantidadeMinima: 5,
    quantidadeReservada: 2,
    unidadeMedida: 'Kg',
    localizacao: 'ARM-02',
    custoMedio: 45.0,
    valorTotal: 360.0,
    ultimaMovimentacao: subDays(3),
  },
];
