/**
 * Dados Mock para desenvolvimento e testes
 */

import { Cliente } from '@/features/crm/types/Cliente.types';

export const clientesMock: Cliente[] = [
  {
    id: '1',
    tipoPessoa: 'juridica',
    razaoSocial: 'Tech Solutions Ltda',
    nomeFantasia: 'TechSol',
    cpfCnpj: '12.345.678/0001-90',
    inscricaoEstadual: '123.456.789.012',
    dataCadastro: new Date('2024-01-15'),
    segmento: 'Corporativo',
    origem: 'Site',
    vendedorResponsavel: 'vendedor1',
    tags: ['VIP', 'Fiel'],
    telefonePrincipal: '(11) 98765-4321',
    whatsapp: '(11) 98765-4321',
    email: 'contato@techsol.com.br',
    site: 'https://www.techsol.com.br',
    contatoPrincipal: 'João Silva',
    cargoContato: 'Gerente de Compras',
    enderecos: [
      {
        id: '1',
        tipo: 'Ambos',
        cep: '01310-100',
        logradouro: 'Av. Paulista',
        numero: '1578',
        complemento: 'Sala 301',
        bairro: 'Bela Vista',
        cidade: 'São Paulo',
        estado: 'SP',
      },
    ],
    limiteCredito: 50000,
    condicaoPagamentoPadrao: '30/60/90',
    tabelaPreco: 'atacado',
    ativo: true,
    criadoEm: new Date('2024-01-15'),
    atualizadoEm: new Date('2024-01-15'),
  },
  {
    id: '2',
    tipoPessoa: 'juridica',
    razaoSocial: 'Escola Internacional Maple',
    nomeFantasia: 'Maple School',
    cpfCnpj: '23.456.789/0001-91',
    inscricaoEstadual: '234.567.890.123',
    dataCadastro: new Date('2024-02-20'),
    segmento: 'Escolas',
    origem: 'Indicação',
    vendedorResponsavel: 'vendedor2',
    tags: ['Educação', 'Potencial'],
    telefonePrincipal: '(11) 3456-7890',
    email: 'compras@mapleschool.com.br',
    site: 'https://www.mapleschool.com.br',
    contatoPrincipal: 'Maria Santos',
    cargoContato: 'Coordenadora',
    enderecos: [
      {
        id: '2',
        tipo: 'Entrega',
        cep: '04547-003',
        logradouro: 'Av. Brigadeiro Faria Lima',
        numero: '2369',
        bairro: 'Jardim Paulistano',
        cidade: 'São Paulo',
        estado: 'SP',
      },
    ],
    limiteCredito: 30000,
    condicaoPagamentoPadrao: '28 dias',
    tabelaPreco: 'especial',
    ativo: true,
    criadoEm: new Date('2024-02-20'),
    atualizadoEm: new Date('2024-02-20'),
  },
  {
    id: '3',
    tipoPessoa: 'fisica',
    razaoSocial: 'Pedro Oliveira',
    cpfCnpj: '123.456.789-00',
    dataCadastro: new Date('2024-03-10'),
    segmento: 'Eventos',
    origem: 'Redes Sociais',
    vendedorResponsavel: 'vendedor1',
    tags: ['Eventos'],
    telefonePrincipal: '(11) 99876-5432',
    whatsapp: '(11) 99876-5432',
    email: 'pedro.oliveira@email.com',
    enderecos: [
      {
        id: '3',
        tipo: 'Faturamento',
        cep: '05436-000',
        logradouro: 'Rua das Fiandeiras',
        numero: '123',
        bairro: 'Vila Olímpia',
        cidade: 'São Paulo',
        estado: 'SP',
      },
    ],
    ativo: true,
    criadoEm: new Date('2024-03-10'),
    atualizadoEm: new Date('2024-03-10'),
  },
  {
    id: '4',
    tipoPessoa: 'juridica',
    razaoSocial: 'Comércio Varejista XYZ',
    nomeFantasia: 'Loja XYZ',
    cpfCnpj: '34.567.890/0001-92',
    inscricaoEstadual: '345.678.901.234',
    dataCadastro: new Date('2025-12-05'),
    segmento: 'Varejo',
    origem: 'Feira/Evento',
    vendedorResponsavel: 'vendedor3',
    tags: ['Varejo', 'Novo'],
    telefonePrincipal: '(11) 2345-6789',
    email: 'contato@lojaxyz.com.br',
    site: 'https://www.lojaxyz.com.br',
    contatoPrincipal: 'Ana Costa',
    cargoContato: 'Gerente',
    enderecos: [
      {
        id: '4',
        tipo: 'Ambos',
        cep: '03040-000',
        logradouro: 'Rua Oriente',
        numero: '567',
        bairro: 'Brás',
        cidade: 'São Paulo',
        estado: 'SP',
      },
    ],
    limiteCredito: 20000,
    condicaoPagamentoPadrao: 'À Vista',
    tabelaPreco: 'varejo',
    ativo: true,
    criadoEm: new Date('2025-12-05'),
    atualizadoEm: new Date('2025-12-05'),
  },
  {
    id: '5',
    tipoPessoa: 'juridica',
    razaoSocial: 'Prefeitura Municipal',
    cpfCnpj: '45.678.901/0001-93',
    dataCadastro: new Date('2024-01-20'),
    segmento: 'Governo',
    origem: 'Prospecção Ativa',
    vendedorResponsavel: 'vendedor2',
    tags: ['Governo', 'VIP'],
    telefonePrincipal: '(11) 4567-8901',
    email: 'licitacao@prefeitura.gov.br',
    contatoPrincipal: 'Carlos Mendes',
    cargoContato: 'Chefe de Compras',
    enderecos: [
      {
        id: '5',
        tipo: 'Faturamento',
        cep: '01310-200',
        logradouro: 'Av. Paulista',
        numero: '1000',
        bairro: 'Bela Vista',
        cidade: 'São Paulo',
        estado: 'SP',
      },
    ],
    limiteCredito: 100000,
    condicaoPagamentoPadrao: '30/60/90',
    tabelaPreco: 'especial',
    ativo: true,
    criadoEm: new Date('2024-01-20'),
    atualizadoEm: new Date('2024-01-20'),
  },
];

// Override do hook para usar dados mock
export const USE_MOCK_DATA = true;
