/**
 * Dados Mock para Oportunidades (Pipeline de Vendas)
 */

import { Oportunidade } from '@/features/crm/types/Oportunidade.types';

export const oportunidadesMock: Oportunidade[] = [
  {
    id: '1',
    nomeCliente: 'Tech Solutions Ltda',
    clienteId: '1',
    valor: 15000,
    probabilidade: 80,
    status: 'proposta_enviada',
    vendedor: 'João Silva',
    vendedorId: 'vendedor1',
    dataUltimaInteracao: new Date('2026-01-25'),
    dataCriacao: new Date('2026-01-10'),
    observacoes: 'Cliente interessado em brindes personalizados para evento corporativo',
    tags: ['Corporativo', 'Urgente'],
  },
  {
    id: '2',
    nomeCliente: 'Escola Internacional Maple',
    clienteId: '2',
    valor: 8500,
    probabilidade: 60,
    status: 'negociacao',
    vendedor: 'Maria Santos',
    vendedorId: 'vendedor2',
    dataUltimaInteracao: new Date('2026-01-26'),
    dataCriacao: new Date('2026-01-15'),
    observacoes: 'Negociando condições de pagamento',
    tags: ['Educação'],
  },
  {
    id: '3',
    nomeCliente: 'Eventos & Cia',
    valor: 12000,
    probabilidade: 40,
    status: 'apresentacao',
    vendedor: 'João Silva',
    vendedorId: 'vendedor1',
    dataUltimaInteracao: new Date('2026-01-24'),
    dataCriacao: new Date('2026-01-20'),
    observacoes: 'Apresentação de catálogo agendada',
    tags: ['Eventos'],
  },
  {
    id: '4',
    nomeCliente: 'Startup XYZ',
    valor: 5000,
    probabilidade: 90,
    status: 'negociacao',
    vendedor: 'Carlos Mendes',
    vendedorId: 'vendedor3',
    dataUltimaInteracao: new Date('2026-01-27'),
    dataCriacao: new Date('2026-01-05'),
    observacoes: 'Pronto para fechar',
    tags: ['Tech', 'VIP'],
  },
  {
    id: '5',
    nomeCliente: 'Prefeitura Municipal',
    clienteId: '5',
    valor: 50000,
    probabilidade: 50,
    status: 'proposta_enviada',
    vendedor: 'Maria Santos',
    vendedorId: 'vendedor2',
    dataUltimaInteracao: new Date('2026-01-23'),
    dataCriacao: new Date('2026-01-08'),
    observacoes: 'Aguardando análise do comitê',
    tags: ['Governo', 'Licitação'],
  },
  {
    id: '6',
    nomeCliente: 'Restaurante Sabor & Arte',
    valor: 3500,
    probabilidade: 30,
    status: 'contato_inicial',
    vendedor: 'João Silva',
    vendedorId: 'vendedor1',
    dataUltimaInteracao: new Date('2026-01-26'),
    dataCriacao: new Date('2026-01-24'),
    observacoes: 'Primeiro contato realizado',
    tags: ['Varejo'],
  },
  {
    id: '7',
    nomeCliente: 'Construtora Alicerce',
    valor: 18000,
    probabilidade: 70,
    status: 'proposta_enviada',
    vendedor: 'Carlos Mendes',
    vendedorId: 'vendedor3',
    dataUltimaInteracao: new Date('2026-01-27'),
    dataCriacao: new Date('2026-01-12'),
    observacoes: 'Orçamento enviado, aguardando feedback',
    tags: ['Corporativo', 'Construção'],
  },
  {
    id: '8',
    nomeCliente: 'Academia Fitness Pro',
    valor: 6800,
    probabilidade: 20,
    status: 'lead_qualificado',
    vendedor: 'Maria Santos',
    vendedorId: 'vendedor2',
    dataUltimaInteracao: new Date('2026-01-25'),
    dataCriacao: new Date('2026-01-22'),
    observacoes: 'Lead qualificado, aguardando agenda',
    tags: ['Saúde'],
  },
];

export const USE_MOCK_OPORTUNIDADES = true;
