-- AlterEnum
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';

-- AlterTable
ALTER TABLE "tenants"
ADD COLUMN "tradeName" VARCHAR(255),
ADD COLUMN "stateReg" VARCHAR(20),
ADD COLUMN "website" VARCHAR(255),
ADD COLUMN "zipCode" VARCHAR(10),
ADD COLUMN "street" VARCHAR(255),
ADD COLUMN "number" VARCHAR(20),
ADD COLUMN "complement" VARCHAR(100),
ADD COLUMN "neighborhood" VARCHAR(100),
ADD COLUMN "city" VARCHAR(100),
ADD COLUMN "state" VARCHAR(2);
